[package]
name = "geometry-cs"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
license-file.workspace = true
repository.workspace   = true
keywords.workspace     = true
categories.workspace   = true
description = "Coordinate system types: Cartesian, Spherical, Geographic, and angle units."
readme = "README.md"

[dependencies]
geometry-coords = { version = "0.0.2", path = "../geometry-coords", default-features = false }

[features]
default = ["std"]
std = ["geometry-coords/std"]
libm = ["geometry-coords/libm"]

[lints]
workspace = true
