[package]
name = "geometry-adapt-nalgebra"
version                = "0.0.8"
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
keywords.workspace     = true
categories.workspace   = true
description = "Adapt nalgebra points and vectors to the geometry-trait concept surface."
readme = "README.md"

[dependencies]
geometry-tag    = { version = "0.0.7", path = "../geometry-tag" }
geometry-coords = { version = "0.0.8", path = "../geometry-coords" }
geometry-cs     = { version = "0.0.8", path = "../geometry-cs" }
geometry-trait  = { version = "0.0.8", path = "../geometry-trait" }
nalgebra        = "0.32"

[dev-dependencies]
geometry-algorithm = { path = "../geometry-algorithm" }

[lints]
workspace = true
