[package]
name = "geometry-trait"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
description = "Concept traits (Point, Linestring, Ring, Polygon, multi-variants, …)."
readme = "README.md"

[features]
default = ["std"]
std = ["geometry-coords/std", "geometry-cs/std"]
libm = ["geometry-coords/libm"]

[dependencies]
geometry-tag    = { version = "0.0.1", path = "../geometry-tag" }
geometry-coords = { version = "0.0.1", path = "../geometry-coords", default-features = false }
geometry-cs     = { version = "0.0.1", path = "../geometry-cs",     default-features = false }

[dev-dependencies]
trybuild        = "1"
geometry-tag    = { version = "0.0.1", path = "../geometry-tag" }      # for trybuild ui fixtures
geometry-coords = { version = "0.0.1", path = "../geometry-coords" }   # bring std for tests
geometry-cs     = { version = "0.0.1", path = "../geometry-cs" }       # bring std for tests

[lints]
workspace = true
